/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import javax.swing.SwingUtilities
import javax.swing.UIManager

fun main() {
    // Configurar Look and Feel del sistema para mejor apariencia
    try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
    } catch (e: Exception) {
        e.printStackTrace()
    }

    // Ejecutar la aplicación en el Event Dispatch Thread de Swing
    SwingUtilities.invokeLater {
        VentanaInicio().isVisible = true
    }
}