/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.util.Scanner

fun main() {
    val reader = Scanner(System.`in`)

    print("Por favor, ingresa tu nombre: ")
    val nombre = reader.nextLine().trim()

    if (nombre.isBlank()) {
        println("Error: Debe ingresar un nombre válido.")
        reader.close()
        return
    }

    val usuario = GestorArchivos.obtenerUsuario(nombre)

    // Inicia nueva sesión y la guarda automáticamente
    usuario.iniciarNuevaSesion()

    println("✅ Sesión registrada correctamente.")
    println("Revisa 'usuarios.txt' y 'sesiones.txt' para el historial.")

    usuario.mostrarHistorial()

    reader.close()
}